# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a386bc4f71e7766df689ac04020c6ff4f8c7a78e6ca02459f44f6cb754770bb16c2c9e0ebe4702e1476e49ec96035ac13c49f6f78bccd51c5faa79fb9e02b9c7

test:
  secret_key_base: 46cd8054ce574ac94e4b3d8b83b2f4714b62f7d9e95c000b4632326698b1d04897b05f803207eb610a4d7ebf78588abda3c62ce175375276a00e22d2760b4035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
